interlay/interbtc-api

src/apis/collateral.ts, src/apis/index.ts, src/apis/treasury.ts, src/mock/apis/collateral.ts, src/mock/apis/treasury.ts, src/mock/polkabtc-api.ts, src/polkabtc-api.ts
=> add collateral and treasury balance getters

package.json
=> bump version to 0.1.18

src/apis/staked-relayer.ts, src/mock/apis/staked-relayer.ts
=> use camelCase for statusUpdate

package.json, src/http/relayer.ts, src/interfaces/definitions.ts
=> add type definitions for status update message

src/http/relayer.ts, src/interfaces/definitions.ts
=> add expired to proposal status enum

package.json, src/apis/issue.ts, src/apis/redeem.ts, src/apis/staked-relayer.ts, src/apis/vaults.ts, src/mock/apis/issue.ts, src/mock/apis/redeem.ts, src/mock/apis/staked-relayer.ts, src/mock/apis/vaults.ts, src/utils/index.ts, src/utils/pagedIterator.ts, test/unit/apis/issue.test.ts, test/unit/apis/redeem.test.ts, test/unit/apis/staked-relayer.test.ts, test/unit/apis/vaults.test.ts
Uses iterators to fetch listings in batches of specified size. It adds the `pagedIterator` generator function to `utils`
=> Add pagination to listings

src/apis/issue.ts, src/apis/redeem.ts, src/http/relayer.ts, src/utils/index.ts, src/utils/logger.ts, test/unit/apis/issue.test.ts, test/unit/apis/vaults.test.ts, tsconfig.json
This PR showcases the usage of such a utlity, by wrapping _issue_ requests with the `sendLoggedTx` util to log all events to console. See `issue.ts`, in the `async request` method.
=> PoC: Add tx event logging util

src/apis/issue.ts, src/apis/redeem.ts
I think that this should work but the return type is a bit tedious so it might be worth having a data structure, probably wrapping `Redeem`, including the ID. What do you think?
=> Add listForUser to issue and redeem

src/http/relayer.ts
=> remove unused relayer json rpc calls

package.json, src/http/client.ts, src/http/index.ts, src/http/relayer.ts, src/http/vault.ts, test/unit/http/staked-relayer.test.ts
=> feat: update json rpc types && implement vault client

package.json, src/apis/vaults.ts, src/mock/apis/vaults.ts
=> feat: optional newCollateral arg for getCollateralization

package.json, src/mock/apis/vaults.ts
=> fix: add wallet typedef to vault

package.json, src/apis/btc-relay.ts
=> feat(btc-relay): get stable confirmations param from btc-relay

src/apis/btc-relay.ts, src/apis/index.ts, src/apis/staked-relayer.ts, src/mock/apis/btc-relay.ts, src/mock/apis/staked-relayer.ts, src/mock/polkabtc-api.ts, src/polkabtc-api.ts, test/integration/apis/btc-relay.test.ts, test/integration/apis/staked-relayer.test.ts
=> feat: expose btc relay js api

package.json, src/polkabtc-api.ts
=> fix(btc-relay): add to polkabtc-api interface

package.json, src/utils/bitcoin.ts
=> feat(bitcoin): util getP2WPKHFromH160 should take network param

package.json, src/utils/bitcoin.ts
=> fix: re-export bitcoin dep for address encoding in ui

src/utils/encoding.ts, src/utils/index.ts, test/unit/utils/encoding.test.ts
=> feat: encoding utils and tests

package.json, src/http/client.ts
=> fix: json rpc client error reporting

package.json
=> fix version bump to 0.4.11

src/apis/issue.ts, src/apis/redeem.ts, src/mock/apis/issue.ts, src/mock/apis/redeem.ts
=> feat: get issue and redeem requests by id

package.json, src/apis/staked-relayer.ts, src/mock/apis/staked-relayer.ts
=> feat: add boolean checks for active / inactive stake

package.json, src/utils/bitcoin.ts, test/unit/utils/bitcoin.test.ts
=> feat: btc address decoder and unit tests

src/apis/collateral.ts, src/mock/apis/collateral.ts, src/polkabtc-api.ts
=> feat: add transfer method for dot collateral

package.json, src/apis/staked-relayer.ts, src/mock/apis/staked-relayer.ts
=> refactor: add active & inactive status update getters

package.json, src/apis/staked-relayer.ts
=> fix: staked-relayer map account id encoding

package.json
…urse is added as new field on redeem request
=> update-types lib: update of version of update-types lib because of reimburse field on redeem request

package.json, src/apis/issue.ts, src/apis/redeem.ts, src/mock/apis/issue.ts, test/integration/apis/issue.test.ts
=> fix: calculate griefing collateral based on input amount

package.json, src/apis/issue.ts, src/apis/redeem.ts, src/mock/apis/issue.ts, test/integration/apis/issue.test.ts
=> fix: calculate griefing collateral based on input amount (#183)

package.json, src/apis/btc-core.ts, src/apis/vaults.ts, src/mock/apis/btc-core.ts, src/mock/apis/vaults.ts
=> feat: expose auction and secure collateral threshold getters

package.json, src/apis/btc-core.ts, src/apis/vaults.ts, src/mock/apis/btc-core.ts, src/mock/apis/vaults.ts
=> feat: expose auction and secure collateral threshold getters (#191)

package.json, src/apis/vaults.ts
=> fix: custom rpcs return bn not big int

package.json, src/apis/issue.ts, src/mock/apis/issue.ts, src/mock/apis/redeem.ts, test/integration/apis/issue.test.ts, test/integration/apis/oracle.test.ts, test/integration/apis/redeem.test.ts, test/integration/apis/staked-relayer.test.ts, test/utils/bitcoin-core-client.ts
=> fix: issue and execute integration tests

src/apis/oracle.ts
=> fix(oracle): check if exchange rate is set to determine liveness

package.json, src/apis/issue.ts, src/apis/redeem.ts, src/apis/staked-relayer.ts, src/apis/vaults.ts, src/mock/apis/issue.ts, src/mock/apis/redeem.ts, src/mock/apis/staked-relayer.ts, src/mock/apis/vaults.ts, test/integration/apis/issue.test.ts, test/integration/apis/redeem.test.ts, test/unit/apis/vaults.test.ts
=> refactor: encode vault wallet addresses

package.json, src/apis/treasury.ts, src/mock/apis/treasury.ts
* feat(transfer): add transfer call on tressury
* renaming of transfer lib call on treasury
* build: fix wrong string
* rename function arguments
* fix linter errors
=> Release 0.7.3

package.json, src/apis/constants.ts, src/mock/apis/refund.ts, src/mock/apis/replace.ts
=> fix: local imports should be relative

package.json, src/apis/btc-core.ts, src/apis/btc-relay.ts, src/apis/constants.ts, src/apis/oracle.ts, src/apis/refund.ts, src/apis/treasury.ts, src/apis/vaults.ts, src/http/faucet.ts, src/mock/apis/refund.ts, src/utils/encoding.ts
=> chore: update esplora-btc-api to 0.4.0

docker-compose.yml, test/integration/apis/vaults.test.ts
=> chore: update docker-compose to use latest parachain and client images

package.json, test/mock/parachain/redeem.ts
=> fix: redeem request struct

package.json, src/parachain/redeem.ts, src/polkabtc-api.ts
Also fixes the burn exchange rate scaling bug
=> Set treasury account

src/parachain/vaults.ts, test/unit/parachain/vaults.test.ts
=> fix: convert issued tokens to BTC

package.json, src/parachain/issue.ts, src/parachain/redeem.ts, src/parachain/replace.ts, src/parachain/transaction.ts, src/parachain/vaults.ts
- Correctly rejects cancelled transactions
- Fixes manual issue and redeem execution
=> fix(transaction): Reject promise on error

src/parachain/vaults.ts, src/utils/currency.ts, test/integration/parachain/staging/vaults.test.ts, test/mock/parachain/vaults.ts, test/unit/parachain/vaults.test.ts
=> fix: get issuable amount for specific vault

package.json, src/parachain/redeem.ts
Will help the bot retry expired redeems
=> fix(redeem): SubscribeToRedeemExpiry callback param

docker-compose.yml, package.json, src/parachain/redeem.ts, src/parachain/vaults.ts, src/utils/issue.ts, test/integration/parachain/staging/issue.test.ts, test/mock/provider.ts
Also extends redeem subscriptions to add `subscribeToRedeemCompletion` (not yet exposed in the interface, needs further testing)
=> chore(test): Upgrade clients

README.md, package.json, src/external/electrs.ts, src/parachain/btc-relay.ts, src/parachain/fee.ts, src/parachain/issue.ts, src/parachain/nomination.ts, src/parachain/oracle.ts, src/parachain/redeem.ts, src/parachain/refund.ts, src/parachain/replace.ts, src/parachain/staked-relayer.ts, src/parachain/tokens.ts, src/parachain/vaults.ts, src/types/currency.ts, src/utils/bitcoin-core-client.ts, src/utils/currency.ts, src/utils/issueRedeem.ts, test/integration/_initialization/staging/initialize.test.ts, test/integration/clients/staging/faucet.test.ts, test/integration/external/staging/electrs.test.ts, test/integration/parachain/release/redeem.test.ts, test/integration/parachain/staging/issue.test.ts, test/integration/parachain/staging/nomination.test.ts, test/integration/parachain/staging/oracle.test.ts, test/integration/parachain/staging/redeem.test.ts, test/integration/parachain/staging/refund.test.ts, test/integration/parachain/staging/replace.test.ts, test/integration/parachain/staging/tokens.test.ts, test/integration/parachain/staging/vaults.test.ts
- Of particular note is how the Tokens module abstracts multiple currencies. This pattern is reused across several files.
- There are also some changes in `src/types/currency.ts` to accommodate the abstraction.
- This PR attempts to add most of the logic required for multi-collateral
=> Monetary.js integration

package.json, src/interbtc-api.ts, src/parachain/vaults.ts
The `backingCollateral` property is hardcoded to the `PolkadotAmount` type at the moment
=> chore: Expose pools API

package.json, src/parachain/issue.ts, src/parachain/redeem.ts, src/parachain/vaults.ts, src/types/requestTypes.ts, src/utils/encoding.ts, src/utils/issueRedeem.ts, test/integration/parachain/staging/issue.test.ts
Next step is to stringify these types in an `index` PR
=> feat: Parse issue and redeem types

docker-compose.yml, package.json, src/parachain/btc-relay.ts, src/parachain/oracle.ts, src/parachain/redeem.ts, src/parachain/replace.ts, src/utils/bitcoin-core-client.ts, src/utils/issueRedeem.ts, src/utils/setup.ts, test/config.ts, test/integration/_initialization/staging/initialize.test.ts, test/integration/clients/staging/faucet.test.ts, test/integration/external/staging/electrs.test.ts, test/integration/parachain/release/redeem.test.ts, test/integration/parachain/staging/issue.test.ts, test/integration/parachain/staging/nomination.test.ts, test/integration/parachain/staging/oracle.test.ts, test/integration/parachain/staging/redeem.test.ts, test/integration/parachain/staging/refund.test.ts, test/integration/parachain/staging/replace.test.ts, test/integration/parachain/staging/tokens.test.ts, test/integration/parachain/staging/vaults.test.ts, test/utils/helpers.ts
=> refactor: optimize and make tests idempotent

package.json
=> chore: bump version to 0.27.0

package.json, src/parachain/tokens.ts
Adds support to get the frozen balance and the transferable balance of an account.
=> feat: add frozen and transferable balance to account

package.json, src/parachain/vaults.ts, test/integration/parachain/staging/vaults.test.ts
- RPC call to the parachain is not working because of a polkadot-js bug
- Reimplements the logic in TS and tests the function
=> Fix required collateral bug

package.json, src/parachain/escrow.ts
- Ensures that positive block numbers are used to estimate the APY/rewards
=> fix: ensure positive and correct APY amount

package.json, src/parachain/rewards.ts
Fixed KINT rewards calculation
=> fix: fixed currency used for rewards tally calculation to use argument instead of hardcoding to collateral

.github/workflows/test-release.yml, scripts/docker-setup.sh
Depends on https://github.com/interlay/parachain-launch/pull/3
=> Integration tests

src/parachain/escrow.ts, src/utils/index.ts, src/utils/rewards.ts, test/unit/utils/rewards.test.ts
Unit tests shouldn't require a parachain connection to run.
=> refactor: separate reward estimation so it can be tested in isolation

package.json
=> chore: disable integration tests in ci

src/parachain/escrow.ts
=> feat: add findBlockEpoch implementation

docker-compose-parachain.yml, docker-compose-standalone.yml, docker/docker-compose-parachain.yml, docker/docker-compose-standalone.yml
Untested but better to be correct for when we fix the integration tests.
=> chore: update docker-compose to latest versions

.github/workflows/test-release.yml, .gitignore, scripts/docker-setup.sh
Stores docker-compose logs and testing coverage results as build artifacts.
=> feat: store build artifacts for docker logs and testing coverage

.github/workflows/test-release.yml, package.json, src/parachain/system.ts, test/integration/parachain/staging/btc-relay.test.ts, test/integration/parachain/staging/sequential/escrow.test.ts, test/integration/parachain/staging/sequential/replace.test.ts
Separated vault replacement tests to individually test success and failure. Unskipped test again.
Other maintenance work.
=> Fix vault replacement request test

.eslintrc.json, package.json, scripts/democracy.ts, scripts/hrmp-setup.ts, src/parachain/asset-registry.ts, src/parachain/escrow.ts, src/parachain/rewards.ts, src/parachain/system.ts, src/parachain/vaults.ts, src/utils/currency.ts, src/utils/encoding.ts, src/utils/rewards.ts, test/helpers.ts, test/integration/external/staging/electrs.test.ts, test/integration/parachain/release/redeem.test.ts, test/integration/parachain/staging/sequential/escrow.test.ts, test/integration/parachain/staging/sequential/issue.test.ts, test/integration/parachain/staging/sequential/oracle.test.ts, test/integration/parachain/staging/sequential/replace.test.ts, test/integration/parachain/staging/sequential/vaults.test.ts, test/integration/parachain/staging/setup/initialize.test.ts, test/integration/parachain/staging/tokens.test.ts, test/unit/mocks/vaultsTestMocks.ts, test/unit/parachain/vaults.test.ts, test/unit/utils/bitcoin.test.ts, test/utils/helpers.ts, tsconfig.json
Fixed/removed obvious errors and warnings.
`yarn fix` will format all files using prettier, and print errors/warnings from eslint.
--------------
Note when using VSCode: to get the most out of these settings, use the parameters below in settings.json (either in the workspace, or as user profile - I use the latter)
```
"editor.inlineSuggest.enabled": true,
"editor.formatOnSave": true,
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.codeActionsOnSave": ["source.formatDocument", "source.fixAll.eslint"],
```
=> fix: update eslintrc and tsconfig for more effective prettier/linting

src/parachain/vaults.ts, test/integration/parachain/staging/sequential/refund.test.ts, test/integration/parachain/staging/sequential/replace.test.ts
A collection of small changes suggested during pull request reviews.
=> Refactor: PR feedback items

scripts/2022-08-08-vault-migration.ts
Used to generate https://kintsugi.subsquare.io/democracy/referendum/56
=> feat: add script for manual vault migration

src/parachain/transaction.ts
Add back optional check for success event type during `DefaultTransactionAPI.sendLogged(...)`.
Also: Add `implements TransactionAPI` to class `DefaultTransactionAPI`.
=> feat (TransactionAPI): add back check for success event type.

test/integration/parachain/staging/sequential/vaults.test.ts, test/integration/parachain/staging/setup/initialize.test.ts
Modify and reenable "should getFees" test in `vaults.test.ts`.
Add missing initializations of vault annuity account to make the test work again.
=> fix (test): should getFees test.

package.json, src/interbtc-api.ts, src/parachain/redeem.ts, src/parachain/system.ts, src/utils/encoding.ts, test/unit/parachain/redeem.test.ts
Return RedeemStatus.Expired where applicable.
=> fix: redeem status expired

scripts/hrmp-setup.ts
Script that I used for the opening with statemine. This will be useful in the future for statemint (and just for future reference)
=> script: open hrmp with statemint/e

scripts/hrmp-setup.ts
This makes the script output the format that I've been using to communicate the extrinsics in discord. It'll save me some manual work and should further reduce opportunity for mistakes
=> chore: improve hrmp opening script output for easy sharing

package.json, src/utils/bitcoin.ts, test/unit/utils/bitcoin.test.ts
Added encoding and decoding of p2wsh (v0) addresses.
Added more unit tests around encoding/decoding for all supported formats.
=> Feat: support p2wsh address

package.json, src/parachain/escrow.ts
Quick fix to revert introduced error during last refactor.
=> Fix staking reward claim

src/parachain/loans.ts, src/types/loans.ts
Updating the types and changing mocks to use Kintsugi currencies.
=> refactor methods, change mocked data

src/parachain/escrow.ts, src/utils/bitcoin.ts, test/unit/utils/bitcoin.test.ts
Merge master branch into wip-feat-interlend to avoid too much drift
=> Chore: merge master

package.json, scripts/runtime-upgrade.ts
Usage:
```shell
yarn runtime-upgrade --with-defaults-of=kintsugi --clients-version=1.17.5 --parachain-version=1.19.1
```
=> feat: add runtime-upgrade script

src/parachain/vaults.ts
Non-critical feedback items from a previous PR: https://github.com/interlay/interbtc-api/pull/464
=> Chore: PR feedback items

scripts/hrmp-setup.ts
=> chore: change hrmp-setup defaults-of to use interlay

package.json, src/parachain/loans.ts, src/types/loans.ts, test/integration/parachain/staging/sequential/loans.test.ts
Opening smaller PR for getter of my borrow positions, last data fetching method needed for the UI.
=> Peter/interlend  my borrow positions impl

package.json
... and move one stray @type import to from dependencies to dev dependencies
=> Chore: update polkadot version, bump lib version

scripts/hrmp-setup.ts
The script is a bit janky but it works so I don't feel inclined to spend more time on it. This script checks the surplus balance of our chain's sovereign accounts on the relay chain, which we need to know when we want to open new xcm channels
=> chore: script to check surplus balance of sovereign account

src/parachain/amm.ts, src/parachain/amm/encoding.ts, src/parachain/amm/index.ts
=> feat(amm): add swap extrinsic

package.json, src/parachain/vaults.ts
=> Fix: remove condition for calling vault reward estimate

src/parachain/system.ts, src/utils/constants.ts, test/integration/parachain/staging/system.test.ts
Adding method for computing what will be the actual block number in X seconds.
=> feat: add util to compute block number in future

src/parachain/amm/trade/utils.ts
Fixing computation of price impact going through stable pools. Computation is based on the curve-js method
https://github.com/curvefi/curve-js/blob/master/src/router.ts#L573
Resolves https://github.com/interlay/interbtc-api/issues/550
=> fix(amm): use price impact computation for stable pools based on curve-js

src/parachain/amm.ts, src/parachain/amm/liquidity-pool/stable.ts, src/parachain/amm/trade/trade.ts, src/parachain/amm/trade/utils.ts
Fixing fee decoding and improving stable pool class.
=> fix(amm): correct decoding of fees and small cleanups

package.json, src/parachain/loans.ts, src/types/loans.ts
=> feat(loans): add supply and borrow caps

src/interbtc-api.ts, src/parachain/btc-relay.ts
=> chore: remove verifyTransactionInclusion

.env.staging, src/utils/encoding.ts, test/integration/parachain/staging/sequential/issue.test.ts, test/integration/parachain/staging/sequential/loans.test.ts, test/integration/parachain/staging/sequential/nomination.test.ts, test/integration/parachain/staging/sequential/redeem.test.ts, test/integration/parachain/staging/sequential/vaults.test.ts, test/integration/parachain/staging/setup/initialize.test.ts, test/utils/helpers.ts
Removes outdated todo notes and better test where we have some magic numbers
=> chore: resolve todos and fixmes

test/integration/parachain/staging/sequential/redeem.test.ts, test/utils/helpers.ts
Opening this PR to discuss the merits of removing / keeping these tests. We anyway test this functionality in the clients repository so I'm not sure it is worth duplicating that here.
=> chore: don't test redeem fee bumping

.github/workflows/integration-tests.yml, package.json, test/integration/external/staging/electrs.test.ts, test/integration/parachain/staging/btc-relay.test.ts, test/integration/parachain/staging/constants.test.ts, test/integration/parachain/staging/fee.test.ts, test/integration/parachain/staging/sequential/asset-registry.test.ts, test/integration/parachain/staging/sequential/escrow.test.ts, test/integration/parachain/staging/sequential/issue.test.ts, test/integration/parachain/staging/sequential/nomination.test.ts, test/integration/parachain/staging/sequential/redeem.test.ts, test/integration/parachain/staging/sequential/replace.test.ts
Catch potential test failures earlier and be explicit about where might take longer
=> chore: reduce or remove most extended timeouts

package.json, src/parachain/constants.ts
Bump Polkadot version to 9.14.2
=> Chore: bump polkadot version

src/parachain/amm.ts, test/integration/parachain/staging/sequential/amm.test.ts
Tests all of the "standard" AMM functionality, still need to add "stable" tests at some point
=> feat: add basic amm test suite

package.json, src/parachain/loans.ts, src/types/loans.ts, test/integration/parachain/staging/sequential/loans.test.ts
Adding more actual incentive reward estimation without user's need to transact with the protocol.
=> fix: add incentive reward estimation

package.json
Update monetary.js to latest `0.7.3`
=> chore: update monetary.js

package.json, src/parachain/redeem.ts, src/parachain/vaults.ts, test/unit/parachain/redeem.test.ts
=> Fix: Return zero max burnable tokens when no liquidation vault exists

scripts/create-proposal.ts, scripts/hrmp-setup.ts, scripts/runtime-upgrade.ts, scripts/util.ts
The hrmp script needed democracy update. I took the opportunity to refactor the code to deduplicate the proposal creation code
=> fix: fix hrmp script and share proposal construction logic

scripts/circulating-supply.ts
Basic script to calculate the current circulating supply of the native token.
=> chore: add circulating supply script
