- src/utils/logger.ts
The callback function passed to `signAndSend` may be called several times (although not necesarrily once for every new event). As such, the Promise only `resolves` when the `isFinalized` property of the callback object is `truthy`. 
The previous implementation worked correctly only when the the callback was called once per tx execution/settlement.
> Fix tx logger promise

- src/apis/staked-relayer.ts
- src/mock/apis/staked-relayer.ts
- test/integration/apis/staked-relayer.test.ts
Adds a new `listIncludingIds` function to the `StakedRelayerAPI`, that returns a list of [id, ActiveStakedRelayer]. The regular `list` function simply returns a list of `ActiveStakedRelayer`s
> List staked relayers with id

- package.json
- src/apis/issue.ts
- src/apis/redeem.ts
- src/apis/vaults.ts
- src/mock/apis/issue.ts
- src/mock/apis/redeem.ts
- src/mock/apis/vaults.ts
- test/integration/apis/vaults.test.ts
The api call cannot be unit tested at the moment, because custom rpc calls are not added to the auto-generated type files. Without rpc types, return values cannot be mocked. I considered manually defining rpc types, but decided it is bad practice. I suppose that in the future polkadot will generate custom rpc type automatically, so this will no longer a problem
> feat(vault): Add api call for fetching replace requests

- src/http/vault.ts
> fix: wrong method name for updateBtcAddress vault call

- package.json
- src/apis/btc-core.ts
- src/mock/apis/btc-core.ts
- test/integration/apis/btc-core.test.ts
- test/unit/apis/btc-core.test.ts
Tested using an op_return that is part of 2 testnet polkaBTC txs, but only the first one has the queried `amount` parameter:
- https://blockstream.info/testnet/tx/f5bcaeb5181154267bf7d05901cc8c2f647414a42126c3aee89e01a2c905ae91?expand
- https://blockstream.info/testnet/tx/4b1900dc48aaa9fa84a340e94aa21d20b54371d19ea6b8edd68a558cd36afdd0?expand
> feat: Add optional amount and recipient params to op_return query

- package.json
- src/external/electrs.ts
- src/parachain/system.ts
Stats/Index needs to subscribe to the latest parachain block number. I exposed a subscription to the entire header in case it becomes useful elsewhere.
Additionally, adds `block_height` return to `getTransactionStatus()`, to optimise away the extra call to `getTransactionBlockHeight` in cases where both the status and the block height are necessary.
> added API to subscribe to new finalized block heads with a callback

- src/parachain/tokens.ts
- src/parachain/vaults.ts
Refactored:
- The current way to get the system capacity would get the issued tokens for every vault. However, this is the same as the total supply of interBTC. Therefore, it's easier to just get the total of interBTC.
- The backing collateral in DOT is already contained in the vault struct, removed that extra call to get the vault twice from the chain.
- Executed some calls in parallel instead of sequentially.
> refactor: reduce number of calls and parallelize to get system capacity

- package.json
- src/external/interbtc-index.ts
- src/interbtc-api.ts
- src/parachain/fee.ts
- src/parachain/index.ts
- src/parachain/nomination.ts
- src/parachain/pools.ts
- src/parachain/redeem.ts
- src/parachain/vaults.ts
- src/utils/encoding.ts
- test/integration/parachain/staging/fee.test.ts
- test/integration/parachain/staging/nomination.test.ts
- test/integration/parachain/staging/redeem.test.ts
- test/integration/parachain/staging/staked-relayer.test.ts
- test/integration/parachain/staging/vaults.test.ts
The bug was on the lib side. Rewards in the `rewards` (global) pool were not scaled down by the nominator's proportion of collateral.
The PR also removes DOT rewards from APY calculation, since these will always be zero.
> fix: Nomination rewards; remove non-interbtc fee getters

- package.json
Importing the lib fails for me without this (please double-check this change isn't only on my end - but I'm very consistently getting output in `build/src/*` in the latest lib version).
> fix(package.json): fixed build paths

- package.json
Fixes this compilation warning:
```
$ ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --package @interlay/interbtc/interfaces --endpoint ./src/json/parachain.json --output ./src/interfaces
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
7.1.1	/home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/node_modules/@polkadot/util
7.1.1	/home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/types/node_modules/@polkadot/util
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager. …
```
> chore: Dedup @polkadot/util

- src/factory.ts
- src/utils/index.ts
to prevent issues when the library is used as a module rather than an executable
> fix(import): avoid exporting the setup script

- package.json
- src/parachain/escrow.ts
- test/integration/parachain/staging/escrow.test.ts
Subtractions of the voting balances were done without saturation, causing them to be negative in some cases.
Thank you to @wliyongfeng for reporting!
> fix(escrow): Saturating subtraction

- package.json
- scripts/hrmp-setup.ts
- scripts/xcm-cross-chain-transfer.ts
- tsconfig.json
Scripts were causing import errors downstream. Moved them outside of `src`
> chore: move unused scripts outside `src`

- package.json
Package version was one patch behind the actual release
> chore: Bump package version

- package.json
- src/parachain/escrow.ts
- src/parachain/issue.ts
- src/parachain/redeem.ts
- src/parachain/system.ts
- test/integration/parachain/staging/escrow.test.ts
- Removes a division by 0 error from the API
- Corrects the escrow reward stake to be a fixed point representation of the amount * unlock_height instead of a monetary amount
- Multiplies the APY by 100 to get a percentage back
- Adds the unlockHeight as parameter for the reward estimate
- Bumps the package version to 1.7.0
> fix: escrow api fixes

- package.json
- src/parachain/vaults.ts
- simplifies filtering for `getVaultsWithIssuableTokens` and `getVaultsWithRedeemableTokens`
- banned vaults are filtered out of the issuable / redeemable tokens result
> fix: Banned vaults have no redeemable tokens

- package.json
- src/parachain/vaults.ts
The object `status.asActive` is always defined when `status.isActive` so this would always filter Vaults as active.
> fix: inactive vaults would show as active

- package.json
- src/external/electrs.ts
cc @savudani8: do you know by any chance why it was set to blockstream.info? Hopefully there's no issue with switching back, since the blockstream API doesn't support querying by opreturn.
> fix:switch to our own esplora/electrs deployment, so that we can use the txindex for opreturns

- package.json
- src/parachain/escrow.ts
- src/parachain/replace.ts
- src/types/requestTypes.ts
- src/utils/encoding.ts
Adds `id` to the `replaceRequestExt` type, so the UI can display it.
UI already attempts to do so (but it's undefined) so this should be a drop-in upgrade.
> feat: track ID in replace requests object

- package.json
- src/parachain/issue.ts
Putting together a skeleton repo for AmsterDOT, looks like the rounding of griefing collateral still fails sometimes.
> fix: issue griefing collateral rounding

- test/unit/utils/encoding.test.ts
Removed in https://github.com/interlay/interbtc-api/pull/338
> chore: recover deleted encoding unit tests

- src/parachain/vaults.ts
I've had to change the type from `Error` to `string` as we're not actually returning an error object (so `e.message` is always undefined).
Has been tested against a local instance of the lib, and it fixed the issue I was seeing on the UI side.
> fix: correct no tokens issued check

- package.json
- src/parachain/oracle.ts
- src/parachain/system.ts
- src/parachain/vaults.ts
- src/types/vault.ts
- test/integration/parachain/staging/sequential/vaults.test.ts
Three basic changes:
- getVaultsWithRedeemableTokens now also includes vaults with status "inactive" as well as "active" (ie. only excludes statuses "liquidated" or "committed theft")
- getPremiumRedeemVaults now applies the same restrictions as getVaultsWithRedeemableTokens as well as the vault's collateral needing to be below the premium redeem threshold.
- extracted shared method to check if vault is active or inactive, and has redeemable tokens.
> Fix premium redeem does not filter banned vaults

- package.json
- src/parachain/vaults.ts
`getBlockRewardAPY` function returns rejected promise when `globalStake` is zero. 
~@bvotteler could you take a look at this? Don't know if this is the best way to handle it. There's a bug when we have zero issued tokens (at https://github.com/interlay/interbtc-api/blob/master/src/parachain/vaults.ts#L497).~
~Dan mentioned that the fix here is to reject the promise - don't know if this is the correct place to reject it though, or if we should be handling this in the `getBlockRewardAPY` function rather than higher up.~
> fix: reject promise if no issued tokens

- scripts/hrmp-setup.ts
Now you only need to modify the consts in the top of the script when using the script for opening new channels. Also you don't have to manually encode relay calls anymore - it's now embedded in this script.
Edit: I also made everything configurable by cli arguments, and added the option to automatically submit a governance proposal with the generated extrinsic.
Example usage: `yarn hrmp-setup --action batched --destination-parachain-id 2085 --refund-hex-address 0xa2e1685f62b2a1a996a2a1ba10ac6836c2b72174cab1bd1c6907454e6365fb70 --submit-proposal`
> feat: improved hrmp channel opening script

- test/integration/parachain/staging/sequential/redeem.test.ts
While we have the odd failing test for fee rate comparisons (BTC tx fee rate vs expected oracle fee rate), add some debug prints for that specific test to better understand where the error might come from.
> test: add temporary debug print for btc tx in fee rate tests

- .github/workflows/test-release.yml
- test/integration/parachain/staging/sequential/redeem.test.ts
- test/utils/helpers.ts
- New test: Check that replace-by-fee for a redeem btc transaction via "bumpfee" rpc command is possible
- Fixed test: Increase permitted delta in btc transaction fee rates to account for observed intermittent fee delta of 1 Satoshi
- Increased Github action timeout to 90 minutes
> Test: Added new test to check if RBF is possible after redeem

- package.json
- src/parachain/redeem.ts
- test/unit/parachain/redeem.test.ts
Fixed burn exchange rate from `x * collateral / (issued + toBeIssued)` to `x * collateral / (issued + toBeIssued - toBeRedeemed)`.
Added unit tests in addition to pre-existing integration tests, particularly for the rejection case.
> Fix burn exchange rate calculation

- package.json
- src/parachain/vaults.ts
Added new API to get vault by account id and collateral currency combination.
The new API `VaultsAPI.getOrNull()` returns null if the vault/currency combo does not exist, in contrast to the existing API `VaultsAPI.get()` which rejects if the vault/currency combo cannot be found.
-----
Note: the PR also contains linter fixes (auto fixed) in a separate commit.
The actual change is at commit [68650db](https://github.com/interlay/interbtc-api/pull/434/commits/68650db92f8a5684f3bccb0949d21bf53ad50118)
The linter change is at commit [8ef77d4](https://github.com/interlay/interbtc-api/pull/434/commits/8ef77d41ecbc5c4656e64efa398426bfd7c21a15)
> Feat: add no vault found response to api

- package.json
- src/interbtc-api.ts
- src/parachain/vaults.ts
- src/types/vault.ts
- test/unit/parachain/vaults.test.ts
Further fixes replacing calculations for issuable tokens with rpc calls which already take custom thresholds for vaults into account.
Bonus: Minor clean up of unused arguments / properties after previous removal of theft reporting
> Fix missed issuable tokens calls

- package.json
- src/parachain/vaults.ts
- src/types/vault.ts
Address missed methods in VaultsAPI and VaultExt to use rpc rather than calculate issuable tokens so the result works with custom collateral thresholds
> Fix missed instance of issuable tokens call (no currency refactor version)

- package.json
- src/parachain/vaults.ts
- src/utils/encoding.ts
Bump interbtc-types to version 1.8.0 (changes to `BalanceWrapper`).
Fix resulting syntax errors.
Moved one helper method out of vaults and into encoding.ts where it can accessed.
> Chore: upgrade interbtc-types 1.8.0

- package.json
- src/parachain/vaults.ts
- test/unit/mocks/vaultsTestMocks.ts
- test/unit/parachain/vaults.test.ts
Add api to allow the connected account to register another collateral currency. Assuming the account id is already running a vault with another collateral currency.
-----
Signature in `VaultsAPI`:
```
/**
* Registers a new vault for the current account ID with a new collateral amount.
* Only applicable if the connected account ID already has a running vault with a different collateral currency.
*
* Rejects with an Error if unable to register.
*
* @param collateralAmount The collateral amount to register the vault with - in the new collateral currency
*/
registerNewCollateralVault(collateralAmount: MonetaryAmount<CollateralCurrencyExt>): Promise<void>;
```
> Feat: add api register new vault collateral

- package.json
- src/parachain/issue.ts
- src/parachain/vaults.ts
- src/types/vault.ts
Add getter to `VaultExt` to get secure collateral threshold for the vault at hand. If no custom threshold is set, it returns the global one (same as `VaultsApi.getSecureCollateralThreshold()`).
Fixed typo in VaultsAPI method `getIssuableTokensFromVault`
> feat: add getter for custom secure collateral threshold

- package.json
- src/parachain/issue.ts
- src/parachain/vaults.ts
- src/types/vault.ts
Add getter to `VaultExt` to get secure collateral threshold for the vault at hand. If no custom threshold is set, it returns the global one (same as `VaultsApi.getSecureCollateralThreshold()`).
Fixed typo in VaultsAPI method getIssuableTokensFromVault
Note: For the most part, cherry-picked from pull request: https://github.com/interlay/interbtc-api/pull/455
> Feat: get custom secure collateral threshold (branch without currency refactor)

- src/external/electrs.ts
- test/integration/external/staging/electrs.test.ts
There may be multiple Bitcoin transactions corresponding to an issue payment, if the user needs to "manually execute" this we should always show the highest amount not the oldest payment since a Vault may trick a user into executing the smaller amount.
We can probably remove or deprecate `getOldestPaymentToRecipientAddressTxId` later.
Not sure if we need to adjust `getTxIdByOpReturn` - would depend on where that is used.
> feat: add electrs helper to get tx by largest payment

- package.json
- src/external/electrs.ts
- test/integration/external/staging/electrs.test.ts
Changes:
- revert name change (from PR https://github.com/interlay/interbtc-api/pull/458),
- mark method as deprecated (use `getLargestPaymentToRecipientAddressTxId` instead),
- bump version
> chore: revert name change for ElectrsAPI.getEarliestPaymentToRecipientAddressTxId

- package.json
- src/parachain/vaults.ts
- test/unit/mocks/vaultsTestMocks.ts
- test/unit/parachain/vaults.test.ts
New method for `VaultsAPI`:
```
/**
* Get the target exchange rate at which a vault will be forced to liquidate, given its
* current locked collateral and issued as well as to be issued tokens.
*
* @param vaultAccountId The vault's account ID
* @param collateralCurrency The collateral currency for the vault with the account id above
* @returns The theoretical collateral per wrapped currency rate below which the vault would be liquidated.
*  Returns undefined if a value cannot be calculated, eg. if the vault has no issued tokens.
*/
getExchangeRateForLiquidation(
vaultAccountId: AccountId,
collateralCurrency: CollateralCurrencyExt
): Promise<Big | undefined>;
```
> feat: add method to get exchange rate for liquidation

- package.json
- src/parachain/asset-registry.ts
- test/integration/parachain/staging/sequential/asset-registry.test.ts
- test/unit/parachain/asset-registry.test.ts
New method for `AssetRegistryApi`:
```
/**
* Get all foreign assets which have a registered collateral ceiling, meaning they can be used as collateral currency.
*
* @returns All foreign assets that have been registered as collateral currency
*/
getCollateralForeignAssets(): Promise<Array<ForeignAsset>>;
```
> Feat: add getter for foreign asset collateral currencies

- package.json
- src/utils/currency.ts
- src/utils/setup.ts
- test/integration/parachain/release/redeem.test.ts
- test/integration/parachain/staging/fee.test.ts
- test/integration/parachain/staging/sequential/issue.test.ts
- test/integration/parachain/staging/sequential/nomination.test.ts
- test/integration/parachain/staging/sequential/oracle.test.ts
- test/integration/parachain/staging/sequential/redeem.test.ts
- test/integration/parachain/staging/sequential/replace.test.ts
- test/integration/parachain/staging/sequential/vaults.test.ts
- test/integration/parachain/staging/setup/initialize.test.ts
- test/integration/parachain/staging/tokens.test.ts
- test/utils/helpers.ts
Fetch collateral currencies based on parachain data, rather than the previously hard-coded token currencies.
The method will now also return foreign assets, as opposed to hard-coded tokens (KINT, INTR, KSM, DOT, etc) only.
------
In `src/utils/currency.ts`
Marked method as deprecated (note of planned removal in the next minor version bump (1.17.0): 
`getCorrespondingCollateralCurrencies(governanceCurrency: GovernanceCurrency): Array<CollateralCurrencyExt>`
To be used instead:
`getCollateralCurrencies(api: ApiPromise, assetRegistry: AssetRegistryAPI): Promise<Array<CollateralCurrencyExt>>`
> Feat: fetch collateral currencies from chain

- src/interbtc-api.ts
- src/parachain/index.ts
- src/parachain/loans.ts
- test/unit/parachain/loans.test.ts
new API: `LoansAPI` with two mocked methods as example.
Added unit tests that are currently meaningless. We can add tests when we add more realistic logic that need tests. For now, this is mostly just a placeholder to have it ready to go.
> Chore: add mocked endpoint as sample.

- src/parachain/asset-registry.ts
- src/types/currency.ts
- test/integration/parachain/staging/setup/initialize.test.ts
- test/unit/parachain/asset-registry.test.ts
New field for `ForeignAsset` - `coingeckoId: string`
Beware that `coingeckoId === ""` if it is not set on the parachain's foreign asset entry.
> feat: add coingeckoId field to ForeignAsset

- package.json
- src/parachain/asset-registry.ts
- src/types/currency.ts
- test/integration/parachain/staging/setup/initialize.test.ts
- test/unit/parachain/asset-registry.test.ts
New field for ForeignAsset - coingeckoId: string
Beware that coingeckoId === "" if it is not set on the parachain's foreign asset entry.
> Feat: add coingecko id field to foreign asset

- package.json
- src/utils/encoding.ts
- test/unit/utils/encoding.test.ts
Fix a bug where the utility method `parseRedeemRequestStatus` returns a pending status when it should return expired and vice versa.
> fix: redeem expiry status

- package.json
- src/parachain/loans.ts
- src/types/loans.ts
- test/integration/parachain/staging/sequential/loans.test.ts
Removing `earnedInterest` field from `LendPosition` because `AccountEarned` storage field is being removed from runtime.
[Context](https://discord.com/channels/745259537707040778/1063145456756064256/1063145460509974568)
> refactor(loans): remove read from AccountEarned storage

- src/parachain/amm.ts
- src/parachain/amm/liquidity-pool/types.ts
- src/types/currency.ts
Rename `LpToken` currency type union to `LpCurrency` to avoid having same name as runtime `LpToken` type.
> fix: rename lib LpToken -> LpCurrency

- package.json
- scripts/create-proposal.ts
Example usage: 
```
❯ yarn create-proposal --url 'https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fapi-kusama.interlay.io%2Fparachain#/extrinsics/decode/0x18000c00000010734b534d10534b534d0000000000000000000000000000000001010103009520040605a10f7f269e903000000000000000000000000000'
```
Output: 
```
Abbreviated input tx:  assetRegistry.registerAsset
**Extrinsic:** https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fapi-kusama.interlay.io%2Fparachain#/extrinsics/decode/0x18000c00000010734b534d10534b534d0000000000000000000000000000000001010103009520040605a10f7f269e903000000000000000000000000000
**Proposal:** https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fapi-kusama.interlay.io%2Fparachain#/extrinsics/decode/0xb90104020208460af818000c00000010734b534d10534b534d0000000000000000000000000000000001010103009520 …
```
> chore: script to create proposals

- scripts/verify-vault-capacity.ts
This script is quite ugly in places but I didn't want to spend time on making it prettier. Committing because it might be useful in hacking together future scripts
> script: verification of vault capacity migration

- scripts/runtime-upgrade.ts
Shamelessly taken from https://github.com/interlay/interbtc-api/pull/554
> chore: set all versions in runtime-upgrade script

- package.json
- src/interbtc-api.ts
- src/parachain/loans.ts
- src/parachain/nomination.ts
- src/parachain/vaults.ts
- src/types/loans.ts
- test/integration/parachain/release/redeem.test.ts
- test/integration/parachain/staging/sequential/loans.test.ts
- test/integration/parachain/staging/sequential/nomination.test.ts
- test/integration/parachain/staging/sequential/redeem.test.ts
- test/integration/parachain/staging/sequential/replace.test.ts
- test/integration/parachain/staging/sequential/vaults.test.ts
- test/unit/parachain/loans.test.ts
- test/utils/helpers.ts
Closes https://github.com/interlay/interbtc-api/issues/567
Breaking changes:
- the `currency` property is removed from `LoanPosition` because it's not required
- `LendPosition` is renamed to `CollateralPosition` because it's easier to distinguish from `LoanPosiiton`
- Unrelated, but since we're make breaking changes: `getBlockRewardAPY` and `computeReward` have their unused parameters removed
> feat(loans): get undercollateralized borrowers

- src/parachain/rewards.ts
- src/parachain/vaults.ts
Unused, related: https://github.com/interlay/interbtc-api/issues/585
> chore: remove unused rewards methods

- src/utils/setup.ts
- src/utils/storage.ts
- test/integration/parachain/staging/sequential/asset-registry.test.ts
- test/integration/parachain/staging/sequential/escrow.test.ts
- test/integration/parachain/staging/sequential/nomination.test.ts
- test/integration/parachain/staging/setup/initialize.test.ts
- test/integration/parachain/staging/utils.test.ts
- test/utils/helpers.ts
Use polkadot-js for storage key / value encoding instead of rolling it ourselves
> refactor: use api for storage setters

- src/parachain/rewards.ts
- src/parachain/vaults.ts
- test/integration/parachain/staging/setup/initialize.test.ts
- test/unit/mocks/vaultsTestMocks.ts
Bundle staking queries and remove "duplicate" call `getLockedCollateral` which only checked reserve balance (anyway unused). Add assertion that computation returns correct amount for aUSD Vault.
Related: https://github.com/interlay/interbtc-api/issues/593
> refactor: use queryMulti for staking computation

- src/parachain/rewards.ts
Not used in the UI so not breaking, but I would like for us to remove the `RewardsAPI` at some point
> chore: remove now unused staking getters

- src/parachain/issue.ts
- src/parachain/redeem.ts
- src/parachain/replace.ts
- src/parachain/system.ts
- src/parachain/vaults.ts
Closes https://github.com/interlay/interbtc-api/issues/353
> refactor: use api.at since At() queries are deprecated

- test/integration/parachain/staging/sequential/issue.test.ts
Seems to already work without changes, not sure why it was skipped before. Left the "FIXME" note since I'm not sure the test would be improved by issuing exactly the allowance of two vaults.
> test: unskip multi-vault issue batching test

- src/parachain/loans.ts
We need to round up, as is done in the parachain: https://github.com/interlay/interbtc/blob/master/crates/loans/src/lib.rs#L1546-L1559
This was changed in https://github.com/interlay/interbtc/pull/896 since rounding down led to possibly free loans. This PR should fix the [open ticket in notion](https://www.notion.so/interlay/Borrow-interest-incorrect-0e9867b36d384361b791970cd8e5d6f6)
> fix: round up lending debt

- package.json
- src/parachain/fee.ts
Hotfix to get rid of slow loading of Vault Dashboard, proper fix will be to update monetary.js `isZero` comparison to not include lower than minimum decimal amounts into account.
> hotfix: update calculateAPY comparison

- scripts/raw-storage-write.ts
This script writes simulates vault liquidations using raw storage writes. We may want to do that again in the future, and even if not, it's a good reference to keep around for how to write to raw storage
> feat: script for writing to raw storage

- package.json
- src/parachain/amm.ts
- src/parachain/amm/liquidity-pool/calculator.ts
- src/parachain/amm/liquidity-pool/stable-meta.ts
- src/parachain/amm/liquidity-pool/stable.ts
- src/parachain/amm/liquidity-pool/standard.ts
- src/parachain/amm/liquidity-pool/utils.ts
- src/parachain/amm/types.ts
Adding `isEmpty` property and returning also empty pools from AMM module.
Closes https://github.com/interlay/interbtc-api/issues/612
> feat(amm): handle empty pools

- src/parachain/escrow.ts
Fix misleading parameter name and add better JSDoc.
> Fix: escrow.getRewardEstimate param name change

- package.json
- src/interbtc-api.ts
- src/parachain/escrow.ts
- test/integration/parachain/staging/sequential/escrow.test.ts
❗ BREAKING ❗ 
Changes the API return value on `escrow.getRewardEstimate`: now returns total reward amount instead of the annualized value.
> Feat: Also return total amount staking on rewards estimate

- package.json
Bumping version for monetary.js update - necessary to be able to update monetary.js on UI side.
> chore: bump version to 2.2.3

- package.json
- src/parachain/loans.ts
Fixes accrued reward calculation to match the decimals used on parachain side.
Solves part of the https://github.com/interlay/interbtc-ui/issues/1265
> fix(loans): make subsidy reward index same as in the parachain

- package.json
Have to bump version to `2.3.3` because of incorrect tagging of `2.3.2` being already released to NPM.
> chore: fix wrong tagging

- scripts/runtime-upgrade.ts
See: https://stackoverflow.com/questions/56295606/typescriptor-javascript-fetch-api-async-await-error-handling
> fix: check for fetching errors in runtime-upgrade script

- package.json
- src/parachain/amm.ts
Fixing farming reward currencies fetching for `amm.getClaimableFarmingRewards` in case the farming rewards are over, but there are still pending unclaimed rewards.
[Thread](https://discord.com/channels/745259537707040778/1123855798611759104/1123855953289293887)
> fix(amm): read farming reward curencies from farmingRewards pallet

- package.json
Updating types to `1.13.0` to contain `Escrow.FreeStakable` call.
> chore: update types

- package.json
- src/factory.ts
- src/interfaces/definitions.ts
Resolves #673 
Add manual runtime definition for `transactionPaymentApi.queryInfo` as quick patch until we are able to properly upgrade to polkadot-js/api `10.3.1` or newer.
> Fix: manual def transactionpaymentapi queryinfo

- docker-compose.yml
- package.json
- src/factory.ts
- src/interfaces/definitions.ts
- test/integration/parachain/staging/system.test.ts
Taken from the changes here: https://github.com/polkadot-js/api/pull/5586
Resolves https://github.com/interlay/interbtc-api/issues/673
Closes https://github.com/interlay/interbtc-api/issues/675
> fix: query payment info

- package.json
- src/interfaces/definitions.ts
- src/interfaces/interbtc-types.ts
Adding `interbtc-types` into the lib directly to solve the following issues:
- `fs.readFile` does not work in the browser, ie. breaks our UI, and
- importing the definitions from `interbtc-types@2.0.1` which exposes it as variable breaks `jest` / `ts-jest`
I wasn't able to find a way to get the definitions imported and the tests to not break, so this PR is a compromise until someone smarter than me manages to fix the import / tests-breaking dilemma.
> Fix: add interbtc types definitions to lib

- package.json
- src/types/index.ts
- src/utils/issueRedeem.ts
`2.6.0-rc.0` -> `2.6.0`
Additional changes:
- export oracle types
> Chore: bump version

- scripts/locked-dot-vdot.ts
A script to gather locked balances for vaults and lending protocol via reserved amounts in `tokens.account`.
Usage:
From project root
```bash
npx tsx ./scripts/locked-dot-vdot.ts [options]
```
Options:
```bash
$ npx tsx ./scripts/locked-dot-vdot.ts --help
Options:
--help          Show help                                        [boolean]
--version       Show version number                              [boolean]
-b, --block-hash    Block hash at which to query, defaults to latest block.
Must be prefixed with '0x' and have a length of 66.
[string]
-o, --output-file   Which file to write json results to, defaults to
'output-{blockhash}.json'                         [string]
-p, --print-only    Do not write results to file, only log to console,
defaults to false.              [boolean] …
```
> Feat: Query locked DOT, VDOT balances
